//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePedido
    {
        public decimal NumeroPedido { get; set; }
        public string Plato { get; set; }
        public decimal Cantidad { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Plato Plato1 { get; set; }
    }
}
